### ISSUE TITLE
With Parameters "sgc -t feat" is broken

### ISSUE THREAD

**Issue by ace3** [JPeer264/node-semantic-git-commit-cli#95]
Hello, 
i tried to run the sgc with -t block, but it's spitting out errors
`(node:6951) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at Object.when (/Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/dest/questions.js:86:46)
    at /Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/run-async/index.js:26:19
    at /Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/inquirer/lib/ui/prompt.js:130:32
    at Observable._subscribe (/Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/rxjs/internal/observable/defer.js:10:21)
    at Observable._trySubscribe (/Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (/Users/ignasius/.nvm/versions/node/v12.18.2/lib/node_modules/semantic-git-commit-cli/node_modules/rxjs/internal/operators/mergeMap.js:82:53)
(node:6951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

i'm using 
nvm v0.35.3
node v12.18.2
npm v6.14.5

thanks.

**Comment by JPeer264** [comment]
Thanks for your issue. Do you have an own `sgcrc` configured? Or does this happen to you out of the box?

**Comment by ace3** [comment]
sorry, it's been a while.

it's occured on both.
configured on macbook
non configured on mac.

**Comment by JPeer264** [comment]
Alright, thanks for the information. I will take a look into it
